virtualbox_bin: upstream updated to 4.0.6

diff --git a/virtualbox_bin/PKGBUILD b/virtualbox_bin/PKGBUILD
--- a/virtualbox_bin/PKGBUILD
+++ b/virtualbox_bin/PKGBUILD
@@ -7,14 +7,15 @@
 # Contributor: iggy <iggy.mfΘgmail·com>
 
 pkgname=virtualbox_bin
-pkgver=4.0.4
-_build=70112
-pkgrel=2
+pkgver=4.0.6
+_build=71344
+pkgrel=3
 pkgdesc='Oracle VM VirtualBox Binary Edition'
 arch=('i686' 'x86_64')
 url='http://virtualbox.org'
 license=('GPL2')
-depends=('libidl2' 'libxcursor' 'libxinerama' 'libxslt' 'curl' 'gcc' 'make' 'kernel26-headers' 'python2')
+depends=('libidl2' 'libxcursor' 'libxinerama' 'libxslt' 'curl' 'kernel26-headers' 'python2')
+options=('!strip')
 optdepends=('virtualbox-ext-oracle: for Oracle extensions'
             'qt: for GUI support'
             'sdl: for VBoxSDL and GUI support'
@@ -25,46 +26,46 @@ optdepends=('virtualbox-ext-oracle: for Oracle extensions'
             'pulseaudio: for PulseAudio support')
 provides=("virtualbox=${pkgver}")
 conflicts=('virtualbox' 'virtualbox-ose' 'virtualbox-modules')
-backup=('etc/conf.d/vbox')
+backup=('etc/vbox/vbox.cfg' 'etc/conf.d/vboxdrv' 'etc/conf.d/vboxweb')
 install='install'
 _arch='x86'
 [ "${CARCH}" = 'x86_64' ] && _arch='amd64'
 source=(
   "VirtualBox-${pkgver}-${_build}-Linux_${_arch}.run::http://download.virtualbox.org/virtualbox/${pkgver}/VirtualBox-${pkgver}-${_build}-Linux_${_arch}.run"
-  'config'
   '10-vboxdrv.rules'
-  'vboxdrv'
-  'vboxweb'
+  'vboxdrv.rc'
+  'vboxdrv.conf'
+  'vboxweb.rc'
+  'vboxweb.conf'
 )
-md5sums=('2a382c44557d06fa7337b045902baaa0'
-         'd61eb2cab419c6250e30975f546e9f66'
-         '98859bfca9ef2ebf2ea43eb9123316fc'
-         'b10ba7fadee69a6a5c9692c0b0262b53'
-         '8bd523861a44efdb82a19a9b7daf0a0c')
-[ "${CARCH}" = 'i686' ] && md5sums[0]='9598e9386cd31984c86381a41f673d7c'
+md5sums=('133cfbb8dc11da780b24f1ef5ef06697'
+         'fe60f9510502bea67383d9198ae8c13c'
+         'c162cfc3683bb8e6970cf08a88b1e4a3'
+         '2d5a0c5275bf660da9f30f75820b6078'
+         'c159d683ba1947290fc2ad2c64194150'
+         '3ac185709bfe688bb753c46e170d0546')
+[[ "${CARCH}" = 'i686' ]] && md5sums[0]='45414b45e5b43e95068b1f3fec71de76'
+_installdir='/opt/VirtualBox'
 
-build() {
+package() {
   # Check and unpack the run package via sh(1)
   sh "VirtualBox-${pkgver}-${_build}-Linux_${_arch}.run" --check
   echo yes | sh "VirtualBox-${pkgver}-${_build}-Linux_${_arch}.run" --target "${srcdir}" \
     --nox11 --noexec &> /dev/null
 
   # Unpack bundled files
-  install -d "${pkgdir}/opt/VirtualBox"
-  cd "${pkgdir}/opt/VirtualBox"
+  install -d "${pkgdir}/${_installdir}"
+  cd "${pkgdir}/${_installdir}"
   tar -xjf "${srcdir}/VirtualBox.tar.bz2"
 
   # Hardened build: Mark binaries suid root, create symlinks for working around
   #                 unsupported $ORIGIN/.. in VBoxC.so and make sure the
   #                 directory is only writable by the user (paranoid).
-  chmod 4511 VirtualBox VBox{SDL,Headless,NetDHCP}
+  chmod 4511 VirtualBox VBox{SDL,Headless,NetDHCP,NetAdpCtl}
   for _lib in VBox{VMM,REM,RT,DDU,XPCOM}.so; do
-    ln -sf "/opt/VirtualBox/${_lib}" "components/${_lib}"
+    ln -sf "${_installdir}/${_lib}" "components/${_lib}"
   done
   chmod go-w .
-
-  # VBoxNetAdpCtl needs to be suid root in any case
-  chmod 4511 VBoxNetAdpCtl
 
   # Replace VirtualBox built-in Qt by system Qt libraries (disabled as of
   # 2010-03-26, 3.1.6-1)
@@ -74,53 +75,83 @@ build() {
   done
 
   # Patch "vboxshell.py" to use Python 2.x instead of Python 3
-  sed -i 's#/usr/bin/python#\02#' "${pkgdir}/opt/VirtualBox/vboxshell.py"
+  sed -i 's#/usr/bin/python#\02#' "${pkgdir}/${_installdir}/vboxshell.py"
 
-  # Install the SDK
-  cd "${pkgdir}/opt/VirtualBox/sdk/installer"
-  VBOX_INSTALL_PATH="/opt/VirtualBox" python2 vboxapisetup.py install --root "${pkgdir}"
-  rm -Rf build
-  cd "${pkgdir}/opt/VirtualBox"
-
-  # Install rc.d scripts
-  install -Dm0755 "${srcdir}/vboxdrv" "${pkgdir}/etc/rc.d/vboxdrv"
-  install -Dm0755 "${srcdir}/vboxweb" "${pkgdir}/etc/rc.d/vboxweb"
-
-  # Update Arch way of life in VBox.sh
-  sed -i -e 's#CONFIG="/etc/vbox/vbox.cfg"#CONFIG="/etc/conf.d/vbox"#' \
-    "${pkgdir}/opt/VirtualBox/VBox.sh"
+  # Update Arch initscripts way of life in VBox.sh
   sed -i -e 's,sudo /etc/init.d/vboxdrv setup,/etc/rc.d/vboxdrv setup,g' \
-    "${pkgdir}/opt/VirtualBox/VBox.sh"
+    "${pkgdir}/${_installdir}/VBox.sh"
   sed -i -e 's,sudo /etc/init.d/vboxdrv restart,/etc/rc.d/vboxdrv restart,g' \
-    "${pkgdir}/opt/VirtualBox/VBox.sh"
+    "${pkgdir}/${_installdir}/VBox.sh"
+
+  # Install vboxdrv initscript
+  install -D -m 0755 "${srcdir}/vboxdrv.rc" "${pkgdir}/etc/rc.d/vboxdrv"
+  install -D -m 0644 "${srcdir}/vboxdrv.conf" "${pkgdir}/etc/conf.d/vboxdrv"
+  
+  # Install vboxweb initscript
+  install -D -m 0755 "${srcdir}/vboxweb.rc" "${pkgdir}/etc/rc.d/vboxweb"
+  install -D -m 0644 "${srcdir}/vboxweb.conf" "${pkgdir}/etc/conf.d/vboxweb"
 
   # Install udev rules
-  install -Dm0644 "${srcdir}/10-vboxdrv.rules" "${pkgdir}/lib/udev/rules.d/10-vboxdrv.rules"
+  install -D -m 0644 "${srcdir}/10-vboxdrv.rules" "${pkgdir}/lib/udev/rules.d/10-vboxdrv.rules"
+  ln -s "${_installdir}/VBoxCreateUSBNode.sh" "${pkgdir}/lib/udev/VBoxCreateUSBNode.sh"
 
-  # Symlink the launchers
-  install -d "${pkgdir}/usr/bin"
+  # Install the SDK
+  cd "${pkgdir}/${_installdir}/sdk/installer"
+  VBOX_INSTALL_PATH="${_installdir}" python2 vboxapisetup.py install --root "${pkgdir}"
+  rm -r -f build
+  cd "${pkgdir}/${_installdir}"
+
+  # Symlink the launchers. Second link can fail if fs is not case sensitive.
+  install -d -m 0755 "${pkgdir}/usr/bin"
   for _bin in VirtualBox VBox{Headless,Manage,SDL,SVC,Tunctl,NetAdpCtl} rdesktop-vrdp; do
-    ln -s "/opt/VirtualBox/${_bin}" "${pkgdir}/usr/bin/${_bin}"
+    ln -s "${_installdir}/${_bin}" "${pkgdir}/usr/bin/${_bin}"
+    ln -s "${_installdir}/${_bin}" "${pkgdir}/usr/bin/${_bin,,}" &>/dev/null || :
   done
 
   # Symlink the desktop icon and ".desktop" files
-  install -d "${pkgdir}/usr/"{share/applications,share/pixmaps}
-  ln -s "/opt/VirtualBox/VBox.png" "${pkgdir}/usr/share/pixmaps/VBox.png"
-  ln -s "/opt/VirtualBox/virtualbox.desktop" "${pkgdir}/usr/share/applications/VirtualBox.desktop"
+  install -d -m 0755 "${pkgdir}/usr/"{share/applications,share/pixmaps}
+  ln -s "${_installdir}/VBox.png" "${pkgdir}/usr/share/pixmaps/VBox.png"
+  ln -s "${_installdir}/icons/128x128/virtualbox.png" "${pkgdir}/usr/share/pixmaps/virtualbox.png"
+  ln -s "${_installdir}/virtualbox.desktop" "${pkgdir}/usr/share/applications/virtualbox.desktop"
 
   # Symlink mime info
-  install -d "${pkgdir}/usr/share/mime/packages"
-  ln -s "/opt/VirtualBox/virtualbox.xml" "${pkgdir}/usr/share/mime/packages/virtualbox.xml"
+  install -d -m 0755 "${pkgdir}/usr/share/mime/packages"
+  ln -s "${_installdir}/virtualbox.xml" "${pkgdir}/usr/share/mime/packages/virtualbox.xml"
 
   # Symlink doc
-  install -d "${pkgdir}/usr/share/doc/${pkgname}"
-  ln -s "/opt/VirtualBox/VirtualBox.chm" "${pkgdir}/usr/share/doc/$pkgname/VirtualBox.chm"
+  install -d -m 0755 "${pkgdir}/usr/share/doc/${pkgname}"
+  ln -s "${_installdir}/VirtualBox.chm" "${pkgdir}/usr/share/doc/$pkgname/virtualbox.chm"
 
-  # Setup default configuration
-  install -Dm0644 "${srcdir}/config" "${pkgdir}/etc/conf.d/vbox"
+  # Symlink module sources
+  install -d -m 0755 "${pkgdir}/usr/src"
+  ln -s "${_installdir}/src/vboxhost" "${pkgdir}/usr/src/vboxhost-${pkgver}"
+
+  # Symlink icons
+  cd "${pkgdir}/${_installdir}/icons"
+  for _dir in *; do
+    cd "${_dir}"
+    install -d -m 0755 "${pkgdir}/usr/share/icons/hicolor/${_dir}/"{apps,mimetypes}
+    for _icon in *; do
+      if [[ "${_icon}" = 'virtualbox.png' ]]; then
+          ln -s "${_installdir}/icons/${_dir}/${_icon}" "${pkgdir}/usr/share/icons/hicolor/${_dir}/apps/${_icon}"
+      else
+          ln -s "${_installdir}/icons/${_dir}/${_icon}" "${pkgdir}/usr/share/icons/hicolor/${_dir}/mimetypes/${_icon}"
+      fi
+    done
+    cd - >/dev/null
+  done
+
+  # Write the configuration file 
+  install -d -m 0755 "${pkgdir}/etc/vbox"
+  echo "# VirtualBox installation directory" > "${pkgdir}/etc/vbox/vbox.cfg"
+  echo "INSTALL_DIR='${_installdir}'" >> "${pkgdir}/etc/vbox/vbox.cfg"
+  echo "# VirtualBox version" >> "${pkgdir}/etc/vbox/vbox.cfg"
+  echo "INSTALL_VER='${pkgver}'" >> "${pkgdir}/etc/vbox/vbox.cfg"
+  echo "INSTALL_REV='${_build}'" >> "${pkgdir}/etc/vbox/vbox.cfg"
+  chmod 0644 "${pkgdir}/etc/vbox/vbox.cfg"
   
   # Create the directory below if it doesn't exist
-  install -d "${pkgdir}/var/run/VirtualBox"
+  install -d -m 0755 "${pkgdir}/var/run/VirtualBox"
 }
 
 # vim:set ts=2 sw=2 ft=sh et:
